version: '3.8'

services:
  db:
    image: postgres:14
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todo_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nnmT0613
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
